if("undefined"!==typeof goog)var Apiomat={Status:{}};"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Status={SCRIPT_ERROR:701,APPLICATION_NOT_ACTIVE:702,BAD_IMAGE:703,BAD_ID:704,CONCURRENT_ACCESS:705,APPLICATION_SANDBOX:706,MODEL_NOT_DEPLOYED:707,WRONG_REF_TYPE:709,ATTRIBUTE_NOT_SET:710,OPERATION_NOT_POSSIBLE:711,APPLICATION_NAME_MISMATCH:712,WRONG_AUTH_HEADER:713,MODEL_STILL_USED:714,COLLECTION_NOT_ALLOWED:715,FB_NO_VALID_MEMBER:716,FB_NO_OAUTH_TOKEN:717,FB_POST_ID_MISSING:718,RESTORE_NO_DUMPS_FOUND:719,TW_NO_VALID_MEMBER:720,TW_NO_OAUTH_TOKEN:721,IMEXPORT_WRONG_ENCODING:722,IMEXPORT_WRONG_CONTENT:723,
PUSH_PAYLOAD_EXCEEDED:724,PUSH_ERROR:725,BAD_EMAIL:726,BAD_PROMOTIONCODE_DISCOUNT:727,BAD_PROMOTIONCODE_CODE:728,PLAN_PRICE:729,PLAN_NO_SYSTEMS:730,SCRIPT_TIME_ERROR:731,INVALID_NAME:732,ATTRIBUTE_IN_SUPERCLASS:733,JSON_TYPE_ERROR:734,TBLR_NO_VALID_MEMBER:735,TBLR_NO_OAUTH_TOKEN:736,TBLR_POST_ID_MISSING:737,LOCATION_INVALID:738,SCRIPT_EXCEPTION:739,BAD_CUSTOMERNAME:740,QUERY_ERROR:708,BAD_TYPE_IN_QUERY:741,UNKNOWN_CLASS_IN_QUERY:742,WRONG_NUM_FORMAT_IN_QUERY:743,QUERY_PARSE_ERROR:744,UNKNOWN_ATTRIBUTE_IN_QUERY:745,
BAD_IMAGE_ALPHA:746,BAD_IMAGE_BGCOLOR:747,BAD_IMAGE_FORMAT:748,FOREIGNID_NOT_SET:749,CLASSES_MISSING:750,INVALID_ATTRIBUTE_TYPE:751,TOKEN_VALUE_EXISTS:752,JSON_FORMAT_ERROR:753,MODULE_DEPLOYMENT:754,BAD_USERNAME:755,APPLICATION_NOT_FOUND:801,CUSTOMER_NOT_FOUND:802,ID_NOT_FOUND:803,MODEL_NOT_FOUND:804,MODULE_NOT_FOUND:805,METAMODEL_NOT_FOUND:806,PLAN_NOT_FOUND:807,PROMOCODE_NOT_FOUND:808,MODULE_USE_FORBIDDEN:820,PUSH_ERROR_APIKEY:821,PUSH_ERROR_CERTIFICATE:822,SAME_NAME_USED_IN_SUPERCLASS:823,PAYMENT_MAX_MODULE:824,
PAYMENT_SYSTEM:825,PAYMENT_DOWNGRADE:826,SAVE_REFERENECE_BEFORE_REFERENCING:827,PAYMENT_DB_SIZE:828,ENDPOINT_PATH_NOT_ALLOWED:829,PAYMENT_NO_CRON:1820,PAYMENT_MODULE_NOT_FREE:1821,NATIVEMODULE_DEACTIVATED:1822,LICENSE_INVALID:1823,PAYMENT_NO_CUSTOMERROLES:1824,ID_EXISTS:830,NAME_RESERVED:831,CIRCULAR_DEPENDENCY:832,NAME_EXISTS:833,UNAUTHORIZED:840,WRONG_APIKEY:841,EVALANCHE_UNAUTH:842,PW_CHANGE_W_TOKEN:843,TOKEN_AUTH_ERROR:844,TOKEN_READ_ONLY:845,CRUD_ERROR:901,IMEXPORT_ERROR:902,COMPILE_ERROR:903,
REFERENCE_ERROR:904,PUSH_PAYLOAD_ERROR:905,PUSH_SEND_ERROR:906,PUSH_INIT_FAILED:907,FACEBOOK_ERROR:908,FACEBOOK_OAUTH_ERROR:910,FACEBOOK_OAUTH_ERROR2:917,MEMBER_NOT_FOUND:911,WORDPRESS_FETCH_DATA_ERROR:912,TUMBLR_OAUTH_ERROR:913,TUMBLR_ERROR:914,EXECUTE_METHOD_ERROR_PRIMITIVE:915,EXECUTE_METHOD_ERROR:916,OAUTH_TOKEN_REQUEST_ERROR:918,FINDING_RESOURCE_ERROR:919,NATIVEMODULE_DEPLOY:920,TOKEN_SEARCH_ERROR:921,MODULE_CONFIG_MISSING:922,HREF_NOT_FOUND:601,WRONG_URI_SYNTAX:602,WRONG_CLIENT_PROTOCOL:603,
IO_EXCEPTION:604,UNSUPPORTED_ENCODING:605,INSTANTIATE_EXCEPTION:606,IN_PERSISTING_PROCESS:607,VERIFY_SOCIALMEDIA:608,TOO_MANY_LOCALIDS:6089,MAX_CACHE_SIZE_REACHED:6090,CANT_WRITE_IN_CACHE:6091,BAD_DATASTORE_CONFIG:610,NO_TOKEN_RECEIVED:611,NO_NETWORK:6092,ID_NOT_FOUND_OFFLINE:6093,ATTACHED_HREF_MISSING:6094,REQUEST_TIMEOUT:6095,SSO_REDIRECT:6096,MALICIOUS_MEMBER:950,getReasonPhrase:function(c){var b=void 0;switch(c){case a.Status.SCRIPT_ERROR:b="Script error!";break;case a.Status.APPLICATION_NOT_ACTIVE:b=
"Application is deactivated!";break;case a.Status.BAD_IMAGE:b="Image format seems to be corrupted!";break;case a.Status.BAD_ID:b="ID format is wrong!";break;case a.Status.CONCURRENT_ACCESS:b="Concurrent access forbidden!";break;case a.Status.APPLICATION_SANDBOX:b="Application is in sandbox mode!";break;case a.Status.MODEL_NOT_DEPLOYED:b="Model is not deployed!";break;case a.Status.WRONG_REF_TYPE:b="Wrong reference type!";break;case a.Status.ATTRIBUTE_NOT_SET:b="Attribute not set!";break;case a.Status.OPERATION_NOT_POSSIBLE:b=
"CRUD operation not possible on this model!";break;case a.Status.APPLICATION_NAME_MISMATCH:b="Application name does not match the one defined in the model!";break;case a.Status.WRONG_AUTH_HEADER:b="Wrong authentication header format, must be 'username:password'";break;case a.Status.MODEL_STILL_USED:b="Model is still used by other attributes, scripts or subclasses!'";break;case a.Status.COLLECTION_NOT_ALLOWED:b="Collection is not supported for this model type!";break;case a.Status.FB_NO_VALID_MEMBER:b=
"Request send from no valid member";break;case a.Status.FB_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";break;case a.Status.FB_POST_ID_MISSING:b="Facebook post id has to be set!";break;case a.Status.RESTORE_NO_DUMPS_FOUND:b="No dumps for app on this date exist!";break;case a.Status.TW_NO_VALID_MEMBER:b="Request send from no valid member";break;case a.Status.TW_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";
break;case a.Status.IMEXPORT_WRONG_ENCODING:b="Wrong Encoding";break;case a.Status.IMEXPORT_WRONG_CONTENT:b="Wrong Filecontent";break;case a.Status.PUSH_PAYLOAD_EXCEEDED:b="Payload size exceeded!";break;case a.Status.PUSH_ERROR:b="Error in push request!";break;case a.Status.BAD_EMAIL:b="eMail format is wrong!";break;case a.Status.BAD_PROMOTIONCODE_DISCOUNT:b="Discount value is wrong!";break;case a.Status.BAD_PROMOTIONCODE_CODE:b="Code is invalid";break;case a.Status.PLAN_PRICE:b="Plan price must be \x3e\x3d 0!";
break;case a.Status.PLAN_NO_SYSTEMS:b="Plan must have at least one system!";break;case a.Status.SCRIPT_TIME_ERROR:b="Script was interrupted, execution took too long.";break;case a.Status.INVALID_NAME:b="Name must start with a letter, followed only by letters or numbers.";break;case a.Status.ATTRIBUTE_IN_SUPERCLASS:b="Attribute is already defined in superclass.";break;case a.Status.JSON_TYPE_ERROR:b="The @type is not correctly defined in your JSON (must be: MODULENAME$CLASSNAME";break;case a.Status.TBLR_NO_VALID_MEMBER:b=
"Request send from no valid member";break;case a.Status.TBLR_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";break;case a.Status.TBLR_POST_ID_MISSING:b="Tumblr post id has to be set!";break;case a.Status.LOCATION_INVALID:b="Location data is invalid (latitude or longitude missing)!";break;case a.Status.SCRIPT_EXCEPTION:b="Exception was raised in script!";break;case a.Status.BAD_CUSTOMERNAME:b="Customer name must contain only characters A-Z,a-z or 0-9!";
break;case a.Status.QUERY_ERROR:b="Query could not be parsed!";break;case a.Status.BAD_TYPE_IN_QUERY:b="The query contains a value with the wrong type";break;case a.Status.UNKNOWN_CLASS_IN_QUERY:b="The definition of the class couldn't be found";break;case a.Status.WRONG_NUM_FORMAT_IN_QUERY:b="A number was supplied in the wrong format";break;case a.Status.QUERY_PARSE_ERROR:b="The query couldn't be parsed";break;case a.Status.UNKNOWN_ATTRIBUTE_IN_QUERY:b="An attribute that was used in the query doesn't exist in the class";
break;case a.Status.BAD_IMAGE_ALPHA:b="alpha is wrong (must be a double value between 0.0 and 1.0)";break;case a.Status.BAD_IMAGE_BGCOLOR:b="bgcolor is wrong (must be an RGB hex value without #, like 'FF0000' for red)";break;case a.Status.BAD_IMAGE_FORMAT:b="format is wrong (can only be png, gif, bmp or jpg/jpeg)";break;case a.Status.FOREIGNID_NOT_SET:b="Foreign ID must be set to a unique value for this model!";break;case a.Status.CLASSES_MISSING:b="Not all classes for this module are contained in the jar! This will lead to compile errors.";
break;case a.Status.INVALID_ATTRIBUTE_TYPE:b="Attributes type is invalid";break;case a.Status.TOKEN_VALUE_EXISTS:b="The token value already exists";break;case a.Status.JSON_FORMAT_ERROR:b="JSON could not be parsed";break;case a.Status.MODULE_DEPLOYMENT:b="Module is currently deploying. Please try again later.";break;case a.Status.BAD_USERNAME:b="User name must not contain a ':'.";break;case a.Status.APPLICATION_NOT_FOUND:b="Application was not found!";break;case a.Status.CUSTOMER_NOT_FOUND:b="Customer was not found!";
break;case a.Status.ID_NOT_FOUND:b="ID was not found!";break;case a.Status.MODEL_NOT_FOUND:b="Model was not found!";break;case a.Status.MODULE_NOT_FOUND:b="Module was not found!";break;case a.Status.METAMODEL_NOT_FOUND:b="Meta Model was not found!";break;case a.Status.PLAN_NOT_FOUND:b="Plan was not found!";break;case a.Status.PROMOCODE_NOT_FOUND:b="Promotion code not valid!";break;case a.Status.MODULE_USE_FORBIDDEN:b="Required module is not attached to app";break;case a.Status.PUSH_ERROR_APIKEY:b=
"No API Key defined for Push service!";break;case a.Status.PUSH_ERROR_CERTIFICATE:b="No certificate defined for Push service!";break;case a.Status.SAME_NAME_USED_IN_SUPERCLASS:b="Same name is already used in a superclass.";break;case a.Status.PAYMENT_MAX_MODULE:b="Maximum number of used modules exceeded for this plan.";break;case a.Status.PAYMENT_SYSTEM:b="Selected system use is not allowed for this plan.";break;case a.Status.PAYMENT_DOWNGRADE:b="Up/Downgrading plans is only allowed for super admins.";
break;case a.Status.SAVE_REFERENECE_BEFORE_REFERENCING:b="Object you are trying to reference is not on the server. Please save it first.";break;case a.Status.PAYMENT_DB_SIZE:b="Used database size exceeds plan";break;case a.Status.ENDPOINT_PATH_NOT_ALLOWED:b="Endpoint not allowed for app; please add path to your app's config.";break;case a.Status.PAYMENT_NO_CRON:b="Cronjobs are not allowed for this plan.";break;case a.Status.PAYMENT_MODULE_NOT_FREE:b="This module is not available for free plan.";break;
case a.Status.NATIVEMODULE_DEACTIVATED:b="Native Module feature is not activated for this installation.";break;case a.Status.LICENSE_INVALID:b="Your license does not allow this action.";break;case a.Status.PAYMENT_NO_CUSTOMERROLES:b="Customer role usage is not available for free plan.";break;case a.Status.ID_EXISTS:b="ID exists!";break;case a.Status.NAME_RESERVED:b="Name is reserved!";break;case a.Status.CIRCULAR_DEPENDENCY:b="One of the parent classes must not be the same class!";break;case a.Status.NAME_EXISTS:b=
"Name is already used!";break;case a.Status.UNAUTHORIZED:b="Authorization failed!";break;case a.Status.WRONG_APIKEY:b="API Key was not correct!";break;case a.Status.EVALANCHE_UNAUTH:b="Authorization failed! Maybe username/password was not set for evelanche configuration?";break;case a.Status.PW_CHANGE_W_TOKEN:b="Not authorized to change a user's password when authenticating with a token.";break;case a.Status.TOKEN_AUTH_ERROR:b="The token could not be authenticated";break;case a.Status.TOKEN_READ_ONLY:b=
"The token can only be used for read requests.";break;case a.Status.CRUD_ERROR:b="Internal error during CRUD operation";break;case a.Status.IMEXPORT_ERROR:b="Error during im/export!";break;case a.Status.COMPILE_ERROR:b="Data models could not be compiled!";break;case a.Status.REFERENCE_ERROR:b="Error in model reference!";break;case a.Status.PUSH_PAYLOAD_ERROR:b="Failed to create payload!";break;case a.Status.PUSH_SEND_ERROR:b="Failed to send message(s)!";break;case a.Status.PUSH_INIT_FAILED:b="Failed to initialize push service!";
break;case a.Status.FACEBOOK_ERROR:b="An error occured while communicating with facebook!";break;case a.Status.FACEBOOK_OAUTH_ERROR:b="facebook throws oAuth error! Please show login dialog again";break;case a.Status.FACEBOOK_OAUTH_ERROR2:b="Received OAuth2 error from Facebook";break;case a.Status.MEMBER_NOT_FOUND:b="Can't find member with this id/username";break;case a.Status.WORDPRESS_FETCH_DATA_ERROR:b="Can't fetch data for wordpress blog";break;case a.Status.TUMBLR_OAUTH_ERROR:b="tumblr threw oAuth error! Please show login dialog again";
break;case a.Status.TUMBLR_ERROR:b="Error communicating with tumblr!";break;case a.Status.EXECUTE_METHOD_ERROR_PRIMITIVE:b="Only primitive types are allowed";break;case a.Status.EXECUTE_METHOD_ERROR:b="Execute method failed";break;case a.Status.OAUTH_TOKEN_REQUEST_ERROR:b="An error occured during requesting an apiOmat OAuth2 token";break;case a.Status.FINDING_RESOURCE_ERROR:b="An error occured while trying to find the resource";break;case a.Status.NATIVEMODULE_DEPLOY:b="Executing onDeploy failed";
break;case a.Status.TOKEN_SEARCH_ERROR:b="An error occured while searching for tokens";break;case a.Status.MODULE_CONFIG_MISSING:b="Your module seems not to be configured properly";break;case a.Status.HREF_NOT_FOUND:b="Model has no HREF; please save it first!";break;case a.Status.WRONG_URI_SYNTAX:b="URI syntax is wrong";break;case a.Status.WRONG_CLIENT_PROTOCOL:b="Client protocol is wrong";break;case a.Status.IO_EXCEPTION:b="IOException was thrown";break;case a.Status.UNSUPPORTED_ENCODING:b="Encoding is not supported";
break;case a.Status.INSTANTIATE_EXCEPTION:b="Error on class instantiation";break;case a.Status.IN_PERSISTING_PROCESS:b="Object is in persisting process. Please try again later";break;case a.Status.VERIFY_SOCIALMEDIA:b="Can't verify against social media provider";break;case a.Status.TOO_MANY_LOCALIDS:b="Can't create more localIDs. Please try again later";break;case a.Status.MAX_CACHE_SIZE_REACHED:b="The maximum cache size is reached.";break;case a.Status.CANT_WRITE_IN_CACHE:b="Can't persist data to cache.";
break;case a.Status.BAD_DATASTORE_CONFIG:b="For requesting a session token without a refresh token, the Datastore must be configured with a username and password";break;case a.Status.NO_TOKEN_RECEIVED:b="The response didn't contain a token";break;case a.Status.NO_NETWORK:b="No network connection available";break;case a.Status.ID_NOT_FOUND_OFFLINE:b="ID was not found in offline storage";break;case a.Status.ATTACHED_HREF_MISSING:b="HREF of attached image / file / reference is missing";break;case a.Status.REQUEST_TIMEOUT:b=
"The request timed out during connecting or reading the response";break;case a.Status.SSO_REDIRECT:b="The request was redirected to an SSO Identity Provider";break;case a.Status.MALICIOUS_MEMBER:b="Malicious use of member detected!";break;default:b="No reason found"}return b},getStatusForCode:function(c){var b=void 0;switch(c){case 701:b=a.Status.SCRIPT_ERROR;break;case 702:b=a.Status.APPLICATION_NOT_ACTIVE;break;case 703:b=a.Status.BAD_IMAGE;break;case 704:b=a.Status.BAD_ID;break;case 705:b=a.Status.CONCURRENT_ACCESS;
break;case 706:b=a.Status.APPLICATION_SANDBOX;break;case 707:b=a.Status.MODEL_NOT_DEPLOYED;break;case 709:b=a.Status.WRONG_REF_TYPE;break;case 710:b=a.Status.ATTRIBUTE_NOT_SET;break;case 711:b=a.Status.OPERATION_NOT_POSSIBLE;break;case 712:b=a.Status.APPLICATION_NAME_MISMATCH;break;case 713:b=a.Status.WRONG_AUTH_HEADER;break;case 714:b=a.Status.MODEL_STILL_USED;break;case 715:b=a.Status.COLLECTION_NOT_ALLOWED;break;case 716:b=a.Status.FB_NO_VALID_MEMBER;break;case 717:b=a.Status.FB_NO_OAUTH_TOKEN;
break;case 718:b=a.Status.FB_POST_ID_MISSING;break;case 719:b=a.Status.RESTORE_NO_DUMPS_FOUND;break;case 720:b=a.Status.TW_NO_VALID_MEMBER;break;case 721:b=a.Status.TW_NO_OAUTH_TOKEN;break;case 722:b=a.Status.IMEXPORT_WRONG_ENCODING;break;case 723:b=a.Status.IMEXPORT_WRONG_CONTENT;break;case 724:b=a.Status.PUSH_PAYLOAD_EXCEEDED;break;case 725:b=a.Status.PUSH_ERROR;break;case 726:b=a.Status.BAD_EMAIL;break;case 727:b=a.Status.BAD_PROMOTIONCODE_DISCOUNT;break;case 728:b=a.Status.BAD_PROMOTIONCODE_CODE;
break;case 729:b=a.Status.PLAN_PRICE;break;case 730:b=a.Status.PLAN_NO_SYSTEMS;break;case 731:b=a.Status.SCRIPT_TIME_ERROR;break;case 732:b=a.Status.INVALID_NAME;break;case 733:b=a.Status.ATTRIBUTE_IN_SUPERCLASS;break;case 734:b=a.Status.JSON_TYPE_ERROR;break;case 735:b=a.Status.TBLR_NO_VALID_MEMBER;break;case 736:b=a.Status.TBLR_NO_OAUTH_TOKEN;break;case 737:b=a.Status.TBLR_POST_ID_MISSING;break;case 738:b=a.Status.LOCATION_INVALID;break;case 739:b=a.Status.SCRIPT_EXCEPTION;break;case 740:b=a.Status.BAD_CUSTOMERNAME;
break;case 708:b=a.Status.QUERY_ERROR;break;case 741:b=a.Status.BAD_TYPE_IN_QUERY;break;case 742:b=a.Status.UNKNOWN_CLASS_IN_QUERY;break;case 743:b=a.Status.WRONG_NUM_FORMAT_IN_QUERY;break;case 744:b=a.Status.QUERY_PARSE_ERROR;break;case 745:b=a.Status.UNKNOWN_ATTRIBUTE_IN_QUERY;break;case 746:b=a.Status.BAD_IMAGE_ALPHA;break;case 747:b=a.Status.BAD_IMAGE_BGCOLOR;break;case 748:b=a.Status.BAD_IMAGE_FORMAT;break;case 749:b=a.Status.FOREIGNID_NOT_SET;break;case 750:b=a.Status.CLASSES_MISSING;break;
case 751:b=a.Status.INVALID_ATTRIBUTE_TYPE;break;case 752:b=a.Status.TOKEN_VALUE_EXISTS;break;case 753:b=a.Status.JSON_FORMAT_ERROR;break;case 754:b=a.Status.MODULE_DEPLOYMENT;break;case 755:b=a.Status.BAD_USERNAME;break;case 801:b=a.Status.APPLICATION_NOT_FOUND;break;case 802:b=a.Status.CUSTOMER_NOT_FOUND;break;case 803:b=a.Status.ID_NOT_FOUND;break;case 804:b=a.Status.MODEL_NOT_FOUND;break;case 805:b=a.Status.MODULE_NOT_FOUND;break;case 806:b=a.Status.METAMODEL_NOT_FOUND;break;case 807:b=a.Status.PLAN_NOT_FOUND;
break;case 808:b=a.Status.PROMOCODE_NOT_FOUND;break;case 820:b=a.Status.MODULE_USE_FORBIDDEN;break;case 821:b=a.Status.PUSH_ERROR_APIKEY;break;case 822:b=a.Status.PUSH_ERROR_CERTIFICATE;break;case 823:b=a.Status.SAME_NAME_USED_IN_SUPERCLASS;break;case 824:b=a.Status.PAYMENT_MAX_MODULE;break;case 825:b=a.Status.PAYMENT_SYSTEM;break;case 826:b=a.Status.PAYMENT_DOWNGRADE;break;case 827:b=a.Status.SAVE_REFERENECE_BEFORE_REFERENCING;break;case 828:b=a.Status.PAYMENT_DB_SIZE;break;case 829:b=a.Status.ENDPOINT_PATH_NOT_ALLOWED;
break;case 1820:b=a.Status.PAYMENT_NO_CRON;break;case 1821:b=a.Status.PAYMENT_MODULE_NOT_FREE;break;case 1822:b=a.Status.NATIVEMODULE_DEACTIVATED;break;case 1823:b=a.Status.LICENSE_INVALID;break;case 1824:b=a.Status.PAYMENT_NO_CUSTOMERROLES;break;case 830:b=a.Status.ID_EXISTS;break;case 831:b=a.Status.NAME_RESERVED;break;case 832:b=a.Status.CIRCULAR_DEPENDENCY;break;case 833:b=a.Status.NAME_EXISTS;break;case 840:b=a.Status.UNAUTHORIZED;break;case 841:b=a.Status.WRONG_APIKEY;break;case 842:b=a.Status.EVALANCHE_UNAUTH;
break;case 843:b=a.Status.PW_CHANGE_W_TOKEN;break;case 844:b=a.Status.TOKEN_AUTH_ERROR;break;case 845:b=a.Status.TOKEN_READ_ONLY;break;case 901:b=a.Status.CRUD_ERROR;break;case 902:b=a.Status.IMEXPORT_ERROR;break;case 903:b=a.Status.COMPILE_ERROR;break;case 904:b=a.Status.REFERENCE_ERROR;break;case 905:b=a.Status.PUSH_PAYLOAD_ERROR;break;case 906:b=a.Status.PUSH_SEND_ERROR;break;case 907:b=a.Status.PUSH_INIT_FAILED;break;case 908:b=a.Status.FACEBOOK_ERROR;break;case 910:b=a.Status.FACEBOOK_OAUTH_ERROR;
break;case 917:b=a.Status.FACEBOOK_OAUTH_ERROR2;break;case 911:b=a.Status.MEMBER_NOT_FOUND;break;case 912:b=a.Status.WORDPRESS_FETCH_DATA_ERROR;break;case 913:b=a.Status.TUMBLR_OAUTH_ERROR;break;case 914:b=a.Status.TUMBLR_ERROR;break;case 915:b=a.Status.EXECUTE_METHOD_ERROR_PRIMITIVE;break;case 916:b=a.Status.EXECUTE_METHOD_ERROR;break;case 918:b=a.Status.OAUTH_TOKEN_REQUEST_ERROR;break;case 919:b=a.Status.FINDING_RESOURCE_ERROR;break;case 920:b=a.Status.NATIVEMODULE_DEPLOY;break;case 921:b=a.Status.TOKEN_SEARCH_ERROR;
break;case 922:b=a.Status.MODULE_CONFIG_MISSING;break;case 601:b=a.Status.HREF_NOT_FOUND;break;case 602:b=a.Status.WRONG_URI_SYNTAX;break;case 603:b=a.Status.WRONG_CLIENT_PROTOCOL;break;case 604:b=a.Status.IO_EXCEPTION;break;case 605:b=a.Status.UNSUPPORTED_ENCODING;break;case 606:b=a.Status.INSTANTIATE_EXCEPTION;break;case 607:b=a.Status.IN_PERSISTING_PROCESS;break;case 608:b=a.Status.VERIFY_SOCIALMEDIA;break;case 6089:b=a.Status.TOO_MANY_LOCALIDS;break;case 6090:b=a.Status.MAX_CACHE_SIZE_REACHED;
break;case 6091:b=a.Status.CANT_WRITE_IN_CACHE;break;case 610:b=a.Status.BAD_DATASTORE_CONFIG;break;case 611:b=a.Status.NO_TOKEN_RECEIVED;break;case 6092:b=a.Status.NO_NETWORK;break;case 6093:b=a.Status.ID_NOT_FOUND_OFFLINE;break;case 6094:b=a.Status.ATTACHED_HREF_MISSING;break;case 6095:b=a.Status.REQUEST_TIMEOUT;break;case 6096:b=a.Status.SSO_REDIRECT;break;case 950:b=a.Status.MALICIOUS_MEMBER}return b}}})("undefined"===typeof exports?Apiomat:exports);if("undefined"!==typeof goog)var XMLHttpRequest={};
if("undefined"===typeof Ti&&"undefined"!==typeof module&&module.exports){var Url=require("url"),spawn=require("child_process").spawn,fs=require("fs");exports.XMLHttpRequest=function(){var a=this,c=require("http"),b=require("https"),e,d,f,g,v,h,x,z=!1,q={"User-Agent":"node-XMLHttpRequest",Accept:"*/*"},p=q,u="accept-charset accept-encoding access-control-request-headers access-control-request-method connection content-length content-transfer-encoding cookie cookie2 date expect host keep-alive origin referer te trailer transfer-encoding upgrade via".split(" "),r=
["TRACE","TRACK","CONNECT"],s=!1,l=!1,k={};this.UNSENT=0;this.OPENED=1;this.HEADERS_RECEIVED=2;this.LOADING=3;this.DONE=4;this.readyState=this.UNSENT;this.onreadystatechange=null;this.responseXML=this.responseText="";this.statusText=this.status=null;this.open=function(a,b,c,k,d){this.abort();l=!1;if(!(a&&-1===r.indexOf(a)))throw"SecurityError: Request method not allowed";f=a;g=b.toString();v="boolean"!==typeof c?!0:c;h=k||null;x=d||null;t(this.OPENED)};this.setDisableHeaderCheck=function(a){z=a};
this.setRequestHeader=function(a,b){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: setRequestHeader can only be called when state is OPEN";if(z||a&&-1===u.indexOf(a.toLowerCase())){if(s)throw"INVALID_STATE_ERR: send flag is true";p[a]=b}else console.warn('Refused to set unsafe header "'+a+'"')};this.getResponseHeader=function(a){return"string"===typeof a&&this.readyState>this.OPENED&&d.headers[a.toLowerCase()]&&!l?d.headers[a.toLowerCase()]:null};this.getAllResponseHeaders=function(){if(this.readyState<
this.HEADERS_RECEIVED||l)return"";var a="",b;for(b in d.headers)"set-cookie"!==b&&"set-cookie2"!==b&&(a+=b+": "+d.headers[b]+"\r\n");return a.substr(0,a.length-2)};this.getRequestHeader=function(a){return"string"===typeof a&&p[a]?p[a]:""};this.send=function(k){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: connection must be opened before send() is called";if(s)throw"INVALID_STATE_ERR: send has already been called";var w=!1,m=!1,n=Url.parse(g),q;switch(n.protocol){case "https:":w=!0;case "http:":q=
n.hostname;break;case "file:":m=!0;break;case void 0:case "":q="localhost";break;default:throw"Protocol not supported.";}if(m){if("GET"!==f)throw"XMLHttpRequest: Only GET method is supported";if(v)fs.readFile(n.pathname,"utf8",function(b,c){b?a.handleError(b):(a.status=200,a.responseText=c,t(a.DONE))});else try{this.responseText=fs.readFileSync(n.pathname,"utf8"),this.status=200,t(a.DONE)}catch(r){this.handleError(r)}}else{var m=n.port||(w?443:80),u=n.pathname+(n.search?n.search:"");p.Host=q;w&&443===
m||80===m||(p.Host+=":"+n.port);h&&("undefined"==typeof x&&(x=""),n=new Buffer(h+":"+x),p.Authorization="Basic "+n.toString("base64"));"GET"===f||"HEAD"===f?k=null:k?(p["Content-Length"]=Buffer.isBuffer(k)?k.length:Buffer.byteLength(k),p["Content-Type"]||(p["Content-Type"]="text/plain;charset\x3dUTF-8")):"POST"===f&&(p["Content-Length"]=0);u={host:q,port:m,path:u,method:f,headers:p,agent:!1};l=!1;if(v){var D=w?b.request:c.request;s=!0;a.dispatchEvent("readystatechange");var E=function(b){d=b;302===
d.statusCode||303===d.statusCode||307===d.statusCode?(g=d.headers.location,b=Url.parse(g),q=b.hostname,e=D({hostname:b.hostname,port:b.port,path:b.path,method:303===d.statusCode?"GET":f,headers:p},E).on("error",F),e.end()):(d.setEncoding("utf8"),t(a.HEADERS_RECEIVED),a.status=d.statusCode,d.on("data",function(b){b&&(a.responseText+=b);s&&t(a.LOADING)}),d.on("end",function(){s&&(t(a.DONE),s=!1)}),d.on("error",function(b){a.handleError(b)}))},F=function(b){a.handleError(b)};e=D(u,E).on("error",F);k&&
e.write(k);e.end();a.dispatchEvent("loadstart")}else{n=".node-xmlhttprequest-content-"+process.pid;m=".node-xmlhttprequest-sync-"+process.pid;fs.writeFileSync(m,"","utf8");k="var http \x3d require('http'), https \x3d require('https'), fs \x3d require('fs');var doRequest \x3d http"+(w?"s":"")+".request;var options \x3d "+JSON.stringify(u)+";var responseText \x3d '';var req \x3d doRequest(options, function(response) {response.setEncoding('utf8');response.on('data', function(chunk) {  responseText +\x3d chunk;});response.on('end', function() {fs.writeFileSync('"+
n+"', 'NODE-XMLHTTPREQUEST-STATUS:' + response.statusCode + ',' + responseText, 'utf8');fs.unlinkSync('"+m+"');});response.on('error', function(error) {fs.writeFileSync('"+n+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');fs.unlinkSync('"+m+"');});}).on('error', function(error) {fs.writeFileSync('"+n+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');fs.unlinkSync('"+m+"');});"+(k?"req.write('"+k.replace(/'/g,"\\'")+"');":"")+"req.end();";for(k=spawn(process.argv[0],
["-e",k]);fs.existsSync(m););a.responseText=fs.readFileSync(n,"utf8");k.stdin.end();fs.unlinkSync(n);a.responseText.match(/^NODE-XMLHTTPREQUEST-ERROR:/)?(k=a.responseText.replace(/^NODE-XMLHTTPREQUEST-ERROR:/,""),a.handleError(k)):(a.status=parseInt(a.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:([0-9]*),.*/,"$1"),10),a.responseText=a.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:[0-9]*,(.*)/,"$1"),t(a.DONE))}}};this.handleError=function(a){this.status=503;this.statusText=a;this.responseText=
a.stack;l=!0;t(this.DONE)};this.abort=function(){e&&(e.abort(),e=null);p=q;this.responseXML=this.responseText="";l=!0;if(this.readyState!==this.UNSENT&&(this.readyState!==this.OPENED||s)&&this.readyState!==this.DONE)s=!1,t(this.DONE);this.readyState=this.UNSENT};this.addEventListener=function(a,b){a in k||(k[a]=[]);k[a].push(b)};this.removeEventListener=function(a,b){a in k&&(k[a]=k[a].filter(function(a){return a!==b}))};this.dispatchEvent=function(b){if("function"===typeof a["on"+b])a["on"+b]();
if(b in k)for(var c=0,d=k[b].length;c<d;c++)k[b][c].call(a)};var t=function(b){a.readyState!==b&&(a.readyState=b,(v||a.readyState<a.OPENED||a.readyState===a.DONE)&&a.dispatchEvent("readystatechange"),a.readyState===a.DONE&&!l&&(a.dispatchEvent("load"),a.dispatchEvent("loadend")))}}};"undefined"!==typeof goog&&(Apiomat.AOMHelper={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMHelper=function(){return{isTitaniumApp:function(){return"object"===typeof Ti},sendEvent:function(c,b){var e=void 0;a.AOMHelper.isTitaniumApp()?Ti.App.fireEvent(c,b||{}):("undefined"!==typeof CustomEvent?e=new CustomEvent(c,b||{}):(e=document.createEvent("Event"),e.initEvent(c,!0,!0),e.customData=b||{}),window.dispatchEvent(e))},addEventListener:function(c,b){a.AOMHelper.isTitaniumApp()?Ti.App.addEventListener(c,b):window.addEventListener(c,b)}}}()})("undefined"===typeof exports?
Apiomat:exports);Array.prototype.filter||(Array.prototype.filter=function(a,c){if(!this)throw new TypeError;var b=Object(this);if("function"!==typeof a)throw new TypeError;var e=[],d;for(d in b)b.hasOwnProperty(d)&&a.call(c,b[d],d,b)&&e.push(b[d]);return e});String.prototype.endsWith||(String.prototype.endsWith=function(a){return-1!==this.indexOf(a,this.length-a.length)});
Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,c=!{toString:null}.propertyIsEnumerable("toString"),b="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),e=b.length;return function(d){if("object"!==typeof d&&("function"!==typeof d||null===d))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in d)a.call(d,g)&&f.push(g);if(c)for(g=0;g<e;g++)a.call(d,b[g])&&f.push(b[g]);return f}}());if("undefined"!==typeof goog)var base64={};
(function(a){if(!a.Base64){var c=function(a){for(var b={},c=0,d=a.length;c<d;c++)b[a.charAt(c)]=c;return b}("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),b=String.fromCharCode,e=function(a){if(2>a.length){var c=a.charCodeAt(0);return 128>c?a:2048>c?b(192|c>>>6)+b(128|c&63):b(224|c>>>12&15)+b(128|c>>>6&63)+b(128|c&63)}c=65536+1024*(a.charCodeAt(0)-55296)+(a.charCodeAt(1)-56320);return b(240|c>>>18&7)+b(128|c>>>12&63)+b(128|c>>>6&63)+b(128|c&63)},d=/[\uD800-\uDBFF][\uDC00-\uDFFFF]|[^\x00-\x7F]/g,
f=function(a){return a.replace(d,e)},g=function(a){var b=[0,2,1][a.length%3];a=a.charCodeAt(0)<<16|(1<a.length?a.charCodeAt(1):0)<<8|(2<a.length?a.charCodeAt(2):0);return["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>18),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>12&63),2<=b?"\x3d":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6&63),1<=b?"\x3d":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a&
63)].join("")},v=a.btoa||function(a){return a.replace(/[\s\S]{1,3}/g,g)},h=function(a,b){return!b?v(f(a)):v(f(a)).replace(/[+\/]/g,function(a){return"+"==a?"-":"_"}).replace(/=/g,"")},x=/[\u00c0-\u00df][\u0080-\u00bf]|[\u00e0-\u00ef][\u0080-\u00bf]{2}|[\u00f0-\u00f7][\u0080-\u00bf]{3}/g,z=function(a){switch(a.length){case 4:return a=((7&a.charCodeAt(0))<<18|(63&a.charCodeAt(1))<<12|(63&a.charCodeAt(2))<<6|63&a.charCodeAt(3))-65536,b((a>>>10)+55296)+b((a&1023)+56320);case 3:return b((15&a.charCodeAt(0))<<
12|(63&a.charCodeAt(1))<<6|63&a.charCodeAt(2));default:return b((31&a.charCodeAt(0))<<6|63&a.charCodeAt(1))}},q=function(a){return a.replace(x,z)},p=function(a){var d=a.length,e=d%4;a=(0<d?c[a.charAt(0)]<<18:0)|(1<d?c[a.charAt(1)]<<12:0)|(2<d?c[a.charAt(2)]<<6:0)|(3<d?c[a.charAt(3)]:0);a=[b(a>>>16),b(a>>>8&255),b(a&255)];a.length-=[0,0,2,1][e];return a.join("")},u=a.atob||function(a){return a.replace(/[\s\S]{1,4}/g,p)},r=function(a){return q(u(a))},s=function(a){return r(a.replace(/[-_]/g,function(a){return"-"==
a?"+":"/"}).replace(/[^A-Za-z0-9\+\/]/g,""))};a.Base64={VERSION:"2.1.2",atob:u,btoa:v,fromBase64:s,toBase64:h,utob:f,encode:h,encodeURI:function(a){return h(a,!0)},btou:q,decode:s};if("function"===typeof Object.defineProperty){var l=function(a){return{value:a,enumerable:!1,writable:!0,configurable:!0}};a.Base64.extendString=function(){Object.defineProperty(String.prototype,"fromBase64",l(function(){return s(this)}));Object.defineProperty(String.prototype,"toBase64",l(function(a){return h(this,a)}));
Object.defineProperty(String.prototype,"toBase64URI",l(function(){return h(this,!0)}))}}}})(this);"undefined"!==typeof goog&&(Apiomat.AOMFileHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMFileHandler=function(){var a={},b=void 0;if("undefined"!==typeof window&&window.File&&window.FileReader&&window.FileList&&window.Blob){var e=function(a){console.log(a.target.error.code)},d=function(a){b=a},f=window.PERSISTENT;!f&&"undefined"!==typeof LocalFileSystem&&(f=LocalFileSystem.PERSISTENT);f&&"undefined"!==typeof window&&window.requestFileSystem&&window.requestFileSystem(f,0,d,e)}this.getAppDirectory=function(a,c){"undefined"!==typeof b?b.root.getDirectory("apiomatpersists",
{create:!0},function(b){a&&a(b)},function(a){console.error("Can't get directory handle!!");c&&c(a)}):a&&a(void 0)};this.getFileHandler=function(a,b,c,d){this.getAppDirectory(function(d){"undefined"!==typeof d?d.getFile(a,{},function(a){b&&b(a)},c):c()},c)};this.getSizeOfAppDir=function(a,c){if("undefined"!==typeof b){var d=this,e=function(a,b,f,g,s,l){f>=a.length?s(g):d.getFileHandler(b,function(b){b.file(function(b){g+=b.size;b=void 0;"undefined"!==typeof a[++f]&&(b=a[f].name);e(a,b,f,g,s,l)},l)},
function(b){b.code!==FileError.NOT_FOUND_ERR&&c?l(b):("undefined"!==typeof a[++f]&&(nextName=a[f].name),e(a,_nextName,f,g,s,l))})},f=function(b){void 0!==typeof b&&0<b.length?e(b,b[0].name,0,0,function(b){a&&a(b)},c):a&&a(0)};this.getAppDirectory(function(a){a.createReader().readEntries(f,c)},c)}else a&&a(0)};this.createFileName=function(a){return a+"_"+(new Date).getTime()};this.removeFile=function(d,e,f){"undefined"!==typeof b?this.getFileHandler(d,function(a){a.remove(function(){e&&e()},f)},function(a){a.code!==
FileError.NOT_FOUND_ERR&&f?f(a):e&&e()}):(delete a[d],e&&e())};this.readFile=function(d,e,f){"undefined"!==typeof b?this.getFileHandler(d,function(a){a.file(function(a){var b=new FileReader;b.onloadend=function(a){e&&e(a.target.result)};b.readAsText(a)})},function(a){a.code!==FileError.NOT_FOUND_ERR&&f?f(a):e&&e(void 0)}):e&&e(a[d])};this.writeFile=function(d,e,f,x){"undefined"!==typeof b?this.getFileHandler(d,function(a){a.createWriter(function(a){a.onwriteend=function(a){f&&f()};a.write(e)},x)},
x,{create:!0,exclusive:!1}):(a[d]=e,f&&f())}};a.AOMFileHandler.HREFMAP_FILENAME="hrefMap";a.AOMFileHandler.USEDLOCALIDS_FILENAME="usedLocalIDs";a.AOMFileHandler.TASKLIST_FILENAME="taskList";a.AOMFileHandler.prototype={}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMNetworkHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMNetworkHandler=function(){return{AOMNETWORKEVENT:"AomNetworkEvent",isChecking:!1,checkForConnection:function(){a.AOMNetworkHandler.isChecking=!0;!1===a.AOMNetworkHandler.isConnected()?setTimeout(a.AOMNetworkHandler.checkForConnection,150):(console.log("Connection is back..."),a.AOMNetworkHandler.isChecking=!1,a.AOMHelper.sendEvent(a.AOMNetworkHandler.AOMNETWORKEVENT,{isConnected:!0}))},isConnected:function(){var c=!0,c=a.AOMHelper.isTitaniumApp()?Titanium.Network.online:navigator.online;
!0===a.forceOffline&&(c=!a.forceOffline);!1===c&&!1===a.AOMNetworkHandler.isChecking&&a.AOMNetworkHandler.checkForConnection();return c}}}()})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMFileHandlerTi={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMFileHandlerTi=function(){var a=function(){var a=Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory,"apiomatpersists");!1===a.exists()&&a.createDirectory();return a};this.getAppDirectory=function(b,e){var d=a();"undefined"===typeof d&&e?e():b&&b(d.nativePath)};this.getSizeOfAppDir=function(b,e){var d=a();"undefined"===typeof d&&e?e():b&&b(d.size)}};a.AOMHelper.isTitaniumApp()&&(a.AOMFileHandlerTi.prototype=new a.AOMFileHandler,a.AOMFileHandlerTi.prototype.constructor=a.AOMFileHandlerTi,
a.AOMFileHandlerTi.prototype.removeFile=function(a,b,e){var d=!1;this.getAppDirectory(function(f){f=Ti.Filesystem.getFile(f,a);f.exists()&&f.writeable&&(d=f.deleteFile());d?b&&b():e&&e()},e)},a.AOMFileHandlerTi.prototype.readFile=function(a,b,e){this.getAppDirectory(function(d){var e=void 0;d=Ti.Filesystem.getFile(d,a);d.exists()&&(e=d.read());e&&"undefined"!==typeof e?b&&b(e.text):b&&b(void 0)},e)},a.AOMFileHandlerTi.prototype.writeFile=function(a,b,e,d){this.getAppDirectory(function(f){Ti.Filesystem.getFile(f,
a).write(b)?e&&e():d&&d()},d)})})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.ApiomatRequestError={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.ApiomatRequestError=function(c,b,e){this.message=e||a.Status.getReasonPhrase(c);this.name="ApiomatRequestError";this.expectedCodes=b;this.statusCode=c;this.getStatusObj=function(){return a.Status.getStatusForCode(this.statusCode)}};a.ApiomatRequestError.prototype=Error();a.ApiomatRequestError.prototype.constructor=a.ApiomatRequestError})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Datastore={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMOfflineStrategy={NO_OFFLINE_HANDLING:0,USE_OFFLINE_CACHE:1};a.AOMAuthType={GUEST:0,USERNAME_PASSWORD:1,OAUTH2_TOKEN:2};a.Datastore=function(){function c(b,c,d,e,f,g,t){r=b;s=c;l=d;k=e;u=f;p=g;n=t;m="undefined"!==typeof n?a.AOMAuthType.OAUTH2_TOKEN:"undefined"!==typeof u&&"undefined"!==typeof p?a.AOMAuthType.USERNAME_PASSWORD:a.AOMAuthType.GUEST}function b(){return{getUsername:function(){return u},getPassword:function(){return p},getAuthType:function(){return m},setUseAsnycRequests:function(a){t=
a},loadFromServer:function(a,b,c,d,e,l){f("GET",a,[200,304],!c?b:{onOk:function(a){b&&b.onOk&&(c.fromJson(a),b.onOk())},onError:function(a){if(b&&b.onError)b.onError(a)}},l,{data:e,withReferencedHrefs:d})},getOrCreateUser:function(b,c){var d=a.User.AOMBASEURL.substring(a.User.AOMBASEURL.lastIndexOf("/")+1),d=r.substring(0,r.indexOf("yambas/rest")+11)+"/modules/facebook/spec/"+d+"/aomuser?facebookToken\x3d"+b;f("GET",d,[200],c,void 0,void 0)},loadResource:function(a,b){f("GET",a,[200,206],b,void 0,
{isByteData:!0})},loadListFromServerWithClass:function(a,b,c,d){f("GET",x(a),[200,304],c,a,{data:b,withReferencedHrefs:d})},postOnServer:function(a,b,c){c||(c=h(a));f("POST",c,[201],b,void 0,{data:a.toJson()})},updateOnServer:function(a,b){var c=a.getHref(),d=a.toJson();f("PUT",c,[200],b,void 0,{data:d})},updateOnServerWithJSON:function(a,b,c){f("PUT",a,[200],c,void 0,{data:b})},deleteOnServer:function(a,b){e(a,void 0,b)},deleteModelOnServer:function(a,b){e(void 0,a,b)},postStaticDataOnServer:function(a,
b,c){b=z(b);this.postStaticDataOnServerWithHref(a,b,c)},postStaticDataOnServerWithHref:function(a,b,c){f("POST",b,[201],c,void 0,{isByteData:!0,data:a})},shouldSendOffline:function(b){return this.getOfflineStrategy()!=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING&&void 0!=this.getOfflineHandler()&&!1===this.getOfflineHandler().isConnected()},getOfflineHandler:function(){return w},getOfflineStrategy:function(){return y},sendOffline:function(b,c,d,e,f){!c&&d instanceof a.AbstractClientDataModel?c=h(d):c||
(c=z(e));this.getOfflineHandler().addTask(b,c,d,e,function(a){if("undefined"!==typeof f&&f.onOk)if("POST"===b&&a)f.onOk(a);else f.onOk()},function(c){"undefined"!==typeof f&&f.onError?("POST"===b&&(c=new a.ApiomatRequestError(a.Status.CRUD_ERROR,201,"Can't save offline")),f.onError(c)):"undefined"!==typeof console&&console.error&&console.error("Can't send request to offline queue: "+c)})},requestSessionToken:function(b){if(m!==a.AOMAuthType.USERNAME_PASSWORD){var c=new a.ApiomatRequestError(a.Status.BAD_DATASTORE_CONFIG);
if("undefined"!==typeof b&&b.onError)b.onError(c);else"undefined"!==typeof console&&console.error&&console.error("Error occured: "+c)}else c=r.substring(r.lastIndexOf("/")+1),d({grant_type:"aom_user",client_id:c,client_secret:s,scope:"read write",username:u,password:p,app:c,system:l},b)},requestSessionTokenWithRefreshToken:function(a,b){var c={grant_type:"refresh_token",client_id:r.substring(r.lastIndexOf("/")+1),client_secret:s,refresh_token:a};d(c,b)},loadCountFromServer:function(a,b,c,d){var e=
void 0,e="string"===typeof a&&"undefined"!==typeof b?a+"/"+b:x(a);f("GET",e+"/count",[200],{onOk:function(a){if(typeof d&&d.onOk)d.onOk(Number(a))},onError:function(a){if(typeof d&&d.onError)d.onError(a)}},void 0,{data:c,returnpost:!0})}}}function e(b,c,d){if(b)f("DELETE",b,[204],d);else if(c&&c.getHref())f("DELETE",c.getHref(),[204],d);else if(b=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND),d&&d.onError)d.onError(b);else console&&console.error&&console.error("Error occured: "+b)}function d(b,
c){var d=r.substring(0,r.indexOf("yambas")+6)+"/oauth/token",e="";for(prop in b)""!==e&&(e+="\x26"),e+=prop+"\x3d"+b[prop];f("POST",d,[200],{onOk:function(a){var b={};a=JSON.parse(a)||{};b.sessionToken=a.access_token;b.refreshToken=a.refresh_token;var d=a.expires_in||0;b.expirationDate=(new Date).getTime()+d;b.module=a.aom_module;b.model=a.aom_model;if("undefined"!==typeof c&&c.onOk)c.onOk(b)},onError:function(b){b=new a.ApiomatRequestError(b.statusCode,200,"Requesting the session token failed");
if("undefined"!==typeof c&&c.onError)c.onError(b);else console&&console.error&&console.error("Error occured: "+b)}},void 0,{data:e,returnpost:!0,headerDetails:{authHeader:!1,contentType:"application/x-www-form-urlencoded"}})}function f(b,c,d,e,f,l){l=l||{};var k=l.data||void 0,n=l.withReferencedHrefs||void 0,y=l.isByteData||!1,m=l.returnpost||!1,w=l.headerDetails||{},h;A?(Ti.API.log("Use HTTP client of titanium"),h=Ti.Network.createHTTPClient({onload:function(a){g(this,d,e,b,f,m,c)},onerror:function(b){var c=
b.error||"";if(-1<c.indexOf("connection failure"))b=new a.ApiomatRequestError(a.Status.NO_NETWORK,d,c);else{if(-1<d.indexOf(this.status))throw b;b=new a.ApiomatRequestError(this.status,d,this.responseText)}if("undefined"!==typeof e&&e.onError)e.onError(b);else Ti.API.error("Received HTTP error: "+b)}})):h="object"===typeof window&&window.XMLHttpRequest?new XMLHttpRequest:C?new exports.XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");"GET"===b&&k&&(c+="?q\x3d"+encodeURIComponent(k));"GET"===b&&
("undefined"!=typeof n&&!0==n)&&(c+="?withReferencedHrefs\x3d"+n);c="http"===c.substring(0,4)?c:"/apps"===c.substring(0,5)?r.substring(0,r.indexOf("/apps"))+c:r+"/"+c;h.open(b,c,t);v(c,b,h,y,w);y&&"GET"===b&&h.overrideMimeType("text/plain; charset\x3dx-user-defined");!1==A&&(h.onreadystatechange=function(){4==h.readyState&&g(h,d,e,b,f,m,c)});("POST"===b||"PUT"===b)&&"undefined"!==typeof k?l&&l.isByteData?(l=k,!1===A&&(l=(new Uint8Array(k)).buffer),h.send(l)):h.send(k):h.send()}function g(b,c,d,e,
f,l,k){var g=!1;try{if(-1<c.indexOf(b.status)){if(d&&d.hasOwnProperty("onOk")){B&&"GET"===e&&b.getResponseHeader("Last-Modified");var t=b.responseText;if("GET"===e&&"undefined"!==typeof f){var n=JSON.parse(t);if(n instanceof Array){t=[];for(k=0;k<n.length;k++){var h=new f;h.fromJson(n[k]);t.push(h)}}else t=new f,t.fromJson(n)}f=void 0;"POST"===e&&!1===l&&(f=b.getResponseHeader("Location"));d.onOk("GET"===e||l?t:f||void 0)}}else g=!0}catch(y){A&&Ti.API.log("Error occured: "+y);if(b&&-1<c.indexOf(b.status))throw y;
g=!0}finally{if(g)if(console.log("Status: "+b.status),b=new a.ApiomatRequestError(b.status,c,b.responseText),"undefined"!==typeof d&&d.onError)d.onError(b);else"undefined"!==typeof console&&console.error&&console.error("Error occured: "+b)}}function v(b,c,d,e,f){d.setRequestHeader("X-apiomat-system",l);d.setRequestHeader("X-apiomat-apikey",s);f.contentType?d.setRequestHeader("Content-Type",f.contentType):"undefined"!==typeof e&&e?d.setRequestHeader("Content-Type","application/octet-stream"):(d.setRequestHeader("Content-Type",
"application/json"),d.setRequestHeader("Accept","application/json"));d.setRequestHeader("X-apiomat-fullupdate","true");if(!(f.hasOwnProperty("authHeader")&&!1==f.authHeader))if(m===a.AOMAuthType.USERNAME_PASSWORD){b=u+":"+p;if(C)try{b=(new (require("buffer").Buffer)(b)).toString("base64")}catch(g){b=Base64.Base64.encode(b)}else try{b=Base64.encode(b)}catch(t){b=Base64.Base64.encode(b)}d.setRequestHeader("Authorization","Basic "+b)}else m===a.AOMAuthType.OAUTH2_TOKEN&&d.setRequestHeader("Authorization",
"Bearer "+n);d.setRequestHeader("X-apiomat-sdkVersion",k);(B||A)&&"GET"===c&&d.setRequestHeader("If-Modified-Since","01.01.1970 00:00:00:00 CEST")}function h(a){var b=r,b=b+"/models/"+a.getModuleName(),b=b+"/";return b+=a.getSimpleName()}function x(a){var b=r,b=b+"/models/"+a.prototype.getModuleName.call(),b=b+"/";return b+=a.prototype.getSimpleName.call()}function z(a){var b=r,b=b+"/data/"+(a?"images":"files");return b+="/"}var q,p,u,r,s,l,k,t=!0,y=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING,w=void 0,
m=a.AOMAuthType.GUEST,n,B="object"===typeof navigator&&0>=navigator.userAgent.indexOf("Chrom")&&-1<navigator.userAgent.indexOf("Safari")||!1,A="object"===typeof Ti||"object"===typeof Titanium,C=!1===A&&"undefined"!==typeof module&&module.exports;return{getInstance:function(){q||(q=b());return q},isInstantiated:function(){return"undefined"!==typeof q&&q},configure:function(a){this.configureWithCredentials(a)},configureWithCredentials:function(b){c(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS,a.User.AOMSDKVERSION,
b.getUserName(),b.getPassword())},configureAsGuest:function(a,b,d,e){c(a,b,d,e)},configureWithUserSessionToken:function(a){this.configureWithSessionToken(a.getSessionToken())},configureWithSessionToken:function(b){c(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS,a.User.AOMSDKVERSION,void 0,void 0,b)},configurePlain:function(a,b,c,d){this.configureAsGuest(a,b,c,d)},setOfflineStrategy:function(b,c){y=b;!w&&y!=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING&&(w=new a.AOMOfflineHandler);!w&&y!=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING&&
(w=new a.AOMOfflineHandler);"undefined"!==typeof w&&("undefined"!==typeof c?w.init(c.onOk||void 0,c.onError||void 0):w.init(void 0,void 0))}}}()})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AbstractClientDataModel={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AbstractClientDataModel=function(){this.data={};this.toJson=function(){this.getHref()&&(this.data.id=this.getID());this.data["@type"]=this.getType();var a=JSON.stringify(this.data);delete this.data.id;return a};this.fromJson=function(a){if("object"===typeof a)for(var b in a)this.data[b]=a[b];else this.data=JSON.parse(a);return this}};a.AbstractClientDataModel.prototype={getModuleName:function(){throw new a.ApiomatRequestError(void 0,void 0,"Must be implemented by child");},getSimpleName:function(){throw new a.ApiomatRequestError(void 0,
void 0,"Must be implemented by child");},getType:function(){return this.getModuleName()+"$"+this.getSimpleName()},getHref:function(){return this.data.href},getRefModelHrefs:function(){return this.data.referencedHrefs},getRefModelHrefsForName:function(a){var b=this.getRefModelHrefs();return b.hasOwnProperty(a)||a in b?b[a]:null},getAllowedRolesGrant:function(){return this.data.allowedRolesGrant},setAllowedRolesGrant:function(a){this.data.allowedRolesGrant=a},getAllowedRolesWrite:function(){return this.data.allowedRolesWrite},
setAllowedRolesWrite:function(a){this.data.allowedRolesWrite=a},getAllowedRolesRead:function(){return this.data.allowedRolesRead},setAllowedRolesRead:function(a){this.data.allowedRolesRead=a},getRstrictResourceAccess:function(){return this.data.restrictResourceAccess},setRestrictResourceAccess:function(a){this.data.restrictResourceAccess=a},getForeignId:function(){return this.data.foreignId},setForeignId:function(a){this.data.foreignId=a},getCreatedAt:function(){return new Date(this.data.createdAt)},
getLastModifiedAt:function(){return new Date(this.data.lastModifiedAt)},getAppName:function(){return this.data.applicationName},load:function(a){this.loadWithHref(void 0,a)},loadAndRefHref:function(a){this.loadWithHrefAndRefHref(void 0,a)},loadWithHref:function(c,b){a.Datastore.getInstance().loadFromServer(c||this.getHref(),b,this,!1)},loadWithHrefAndRefHref:function(c,b){a.Datastore.getInstance().loadFromServer(c||this.getHref(),b,this,!0)},save:function(c,b){b="undefined"!==typeof b&&b.constructor===
Boolean?b:!0;var e={onOk:function(a){!this.parent.getHref()&&a&&(this.parent.data.href=a);this.parent.setOffline(this.wasLocalSave||!1);if(!this.wasLocalSave&&b)this.parent.load({onOk:function(){if(c&&c.onOk)c.onOk()},onError:function(a){if(c&&c.onError)c.onError(a)}});else if(c&&c.onOk)c.onOk()},onError:function(a){if(c&&c.onError)c.onError(a)},parent:this};this.getHref()?a.Datastore.getInstance().shouldSendOffline("PUT")?(e.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("PUT",this.getHref(),
this,void 0,e)):a.Datastore.getInstance().updateOnServer(this,e):a.Datastore.getInstance().shouldSendOffline("POST")?(e.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("POST",void 0,this,void 0,e)):a.Datastore.getInstance().postOnServer(this,e)},deleteModel:function(c){a.Datastore.getInstance().shouldSendOffline("DELETE")?a.Datastore.getInstance().sendOffline("DELETE",this.getHref(),this,void 0,c):a.Datastore.getInstance().deleteModelOnServer(this,c)},isOffline:function(){return this.data.isOffline||
!1},setOffline:function(a){this.data.isOffline=a},getID:function(){return this.getHref().substring(this.getHref().lastIndexOf("/")+1)}}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMOfflineInfo={},Apiomat.AOMOfflineHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMOfflineInfo=function(a,b,e,d,f,g,v){this.httpMethod=a;this.fileKey=e;this.timestamp=d;this.url=b;this.clazz=d;this.localId=f;this.refName=g;this.isStaticData=v};a.AOMOfflineHandler=function(){a.AOMOfflineHandler.AOMTASKEVENT="AomTaskEvent";var c=[],b={},e={},d=[],f=new a.AOMFileHandler;a.AOMHelper.isTitaniumApp()&&(f=new a.AOMFileHandlerTi);a.AOMHelper.addEventListener(a.AOMNetworkHandler.AOMNETWORKEVENT,function(a){v()});var g=function(a,b,c,d){f.readFile(a,function(a){a&&JSON.parse(a);
c&&c()},function(b){console.error("Error on restoring content of "+a+" --\x3e "+b.code);d&&d(b)})},v=function(){if(1>c.length)b={},u();else if(!1!==a.AOMNetworkHandler.isConnected()){var e=c.shift();delete d[e.localId];r();f.readFile(e.fileKey,function(a){f.removeFile(e.fileKey);if(a&&!1===e.isStaticData){var b=new e.clazz;b.fromJson(a);a=b}(a||e.isStaticData&&e.url)&&x(e,a,e.isStaticData)},function(a){console.error("Error occured on reading file "+a)})}},h={extCallback:void 0,onOk:function(a){if(h.extCallback&&
h.extCallback.onOk)h.extCallback.onOk(a);v()},onError:function(a){if(h.extCallback&&h.extCallback.onError)h.extCallback.onError(a);v()}},x=function(c,d,f){var g=c.url,w=void 0!=c.refName&&0<c.refName.length;switch(c.httpMethod){case "POST":w&&!1===f&&(g=g.substring(g.lastIndexOf("/")+1),q(d),g=b[g]+"/"+c.refName);h.extCallback={onOk:function(d){if(null!=d&&0<d.length){b[c.localId]=d;u();if(!1===f){var g=c.localId;if((model=e[g])&&model.isOffline())delete e[g],model.data.href=d,model.setOffline(!1)}a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c,href:d})}},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c,href:m})}};g?f?a.Datastore.getInstance().postStaticDataOnServerWithHref(d,g,h):a.Datastore.getInstance().postOnServer(d,h,g):a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:error,info:c,href:m});break;case "PUT":var m=q(d);void 0!==m&&0<m.length?(h.extCallback={onOk:function(){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c})},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c})}},a.Datastore.getInstance().updateOnServer(d,h)):a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:a.Status.HREF_NOT_FOUND,info:c});break;case "DELETE":m=void 0,m=f?p(g):q(d),w&&(g=g.substring(g.lastIndexOf("/")+1),m=b[g]+"/"+c.refName+"/"+m.substring(m.lastIndexOf("/")+1)),m&&0<m.length?(h.extCallback={onOk:function(){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c})},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c})}},w||f?a.Datastore.getInstance().deleteOnServer(m,h):a.Datastore.getInstance().deleteModelOnServer(d,h)):a.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:a.Status.HREF_NOT_FOUND,info:c})}},z=function(){for(var b=0,c=Math.floor(1E6*Math.random()+1);d[c]&&5>b;)b++,c=Math.floor(1E6*Math.random()+1);if(4<=b)throw new a.ApiomatRequestError(a.Status.TOO_MANY_LOCALIDS);
return c},q=function(a){var c=a.getHref();if(a.isOffline()){var d=a.getID();if(void 0!==d&&0<d.length&&(d=b[d]))c=d,a.data.href=c;for(var e in a.data)e.endsWith("URL")&&(d=p(a.data[e]))&&(a.data[e]=d)}return c},p=function(a){a=a.substring(a.lastIndexOf("/")+1);return b[a]},u=function(){return f.writeFile(a.AOMFileHandler.HREFMAP_FILENAME,JSON.stringify(b))},r=function(){f.writeFile(a.AOMFileHandler.USEDLOCALIDS_FILENAME,JSON.stringify(d));f.writeFile(a.AOMFileHandler.TASKLIST_FILENAME,JSON.stringify(c))},
s=function(b,c,d,e){var g=void 0;f.getSizeOfAppDir(function(h){h&&h>=1024*this.cacheSizeInMB?(console.error("Max cache size is reached. Can't add to cache!"),e&&e(new a.ApiomatRequestError(a.Status.MAX_CACHE_SIZE_REACHED))):(g=f.createFileName(c),f.writeFile(g,b||"",function(){d&&d(g)},function(b){console.error("Can't persist to cache: "+b.code);e&&e(new a.ApiomatRequestError(a.Status.CANT_WRITE_IN_CACHE))}))})};this.cacheSizeInMB=4;this.addTask=function(b,d,f,g,h,m){var n=d,p=!1===f instanceof a.AbstractClientDataModel,
v=f;!1===p&&(v=f.toJson());var q=void 0;if("POST"===b){try{q=z()}catch(u){throw u;}n+="/"+(g?g+"/":"")+q;!1===p&&(e[q]=f)}s(v,q||b,function(e){e&&(e=new a.AOMOfflineInfo(b,d,e,f?f.constructor:void 0,q,g,p),c.push(e),r());h&&h(n)},function(a){console.error("Got error on adding task to offline queue: "+a);m&&m(a)})};this.init=function(e,f){var h=function(){g(a.AOMFileHandler.USEDLOCALIDS_FILENAME,d,function(){v();"undefined"!==typeof e&&e()},function(a){"undefined"!==typeof f&&f(a)})},p=function(){g(a.AOMFileHandler.HREFMAP_FILENAME,
b,function(){h()},function(a){h()})};g(a.AOMFileHandler.TASKLIST_FILENAME,c,function(){p()},function(a){p()})};this.isConnected=function(){return a.AOMNetworkHandler.isConnected()};this.clearCache=function(){b={};u();for(var a=0,d=c.length;a<d;a++){var g=c[a];g.fileKey&&f.removeFile(g.fileKey)}e={};c=[];r()}}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Poll={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Poll=function(){this.init()};a.Poll.getPolls=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Poll,c,b,!1)};a.Poll.getPollsAndRefHref=function(c,b,e){a.Datastore.getInstance().loadListFromServerWithClass(a.Poll,c,b,e)};a.Poll.getPollsCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Poll,void 0,c,b)};a.Poll.prototype=new a.AbstractClientDataModel;a.Poll.prototype.constructor=a.Poll;a.Poll.prototype.init=function(){this.data={}};a.Poll.prototype.getSimpleName=
function(){return"Poll"};a.Poll.prototype.getModuleName=function(){return"TaksiMain"};a.Poll.prototype.getAlamat=function(){return this.data.alamat};a.Poll.prototype.setAlamat=function(a){this.data.alamat=a};a.Poll.prototype.getKota=function(){return this.data.kota};a.Poll.prototype.setKota=function(a){this.data.kota=a};a.Poll.prototype.getLatitude=function(){return this.data.latitude};a.Poll.prototype.setLatitude=function(a){this.data.latitude=a};a.Poll.prototype.getLongitude=function(){return this.data.longitude};
a.Poll.prototype.setLongitude=function(a){this.data.longitude=a};a.Poll.prototype.getNama_perusahaan=function(){return this.data.nama_perusahaan};a.Poll.prototype.setNama_perusahaan=function(a){this.data.nama_perusahaan=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Pegawai={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Pegawai=function(){this.init()};a.Pegawai.getPegawais=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Pegawai,c,b,!1)};a.Pegawai.getPegawaisAndRefHref=function(c,b,e){a.Datastore.getInstance().loadListFromServerWithClass(a.Pegawai,c,b,e)};a.Pegawai.getPegawaisCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Pegawai,void 0,c,b)};a.Pegawai.prototype=new a.AbstractClientDataModel;a.Pegawai.prototype.constructor=a.Pegawai;a.Pegawai.prototype.init=
function(){this.data={}};a.Pegawai.prototype.getSimpleName=function(){return"Pegawai"};a.Pegawai.prototype.getModuleName=function(){return"TaksiMain"};a.Pegawai.prototype.getFotoURL=function(c,b,e,d,f){var g=this.data.fotoURL;if(g)return g+=".img?apiKey\x3d"+a.User.AOMAPIKEY+"\x26system\x3d"+a.User.AOMSYS,c&&(g+="\x26width\x3d"+c),b&&(g+="\x26height\x3d"+b),e&&(g+="\x26bgcolor\x3d"+e),d&&(g+="\x26alpha\x3d"+d),f&&(g+="\x26format\x3d"+f),g};a.Pegawai.prototype.loadFoto=function(c,b,e,d,f,g){c=this.getFotoURL(c,
b,e,d,f);if("undefined"==typeof c)throw new a.ApiomatRequestError(a.Status.ATTACHED_HREF_MISSING,200);return a.Datastore.getInstance().loadResource(c,g)};a.Pegawai.prototype.postFoto=function(c,b){var e={onOk:function(c){if(c)this.parent.data.fotoURL=c,this.parent.save({onOk:function(){if(b&&b.onOk)b.onOk()},onError:function(e){a.Datastore.getInstance().deleteOnServer(c,{onOk:function(){if(b&&b.onError)b.onError(e)},onError:function(a){if(b&&b.onError)b.onError(e)}});delete this.parent.data.fotoURL}});
else{var e=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND);if(b&&b.onError)b.onError(e);else console&&console.log&&console.log("Error occured: "+e)}},onError:function(a){if(b&&b.onError)b.onError(a)},parent:this};a.Datastore.getInstance().shouldSendOffline("POST")?a.Datastore.getInstance().sendOffline("POST",null,c,!0,e):a.Datastore.getInstance().postStaticDataOnServer(c,!0,e)};a.Pegawai.prototype.deleteFoto=function(c){var b=this.data.fotoURL,e={onOk:function(){delete this.parent.data.fotoURL;
this.parent.save({onOk:function(){if(c&&c.onOk)c.onOk()},onError:function(a){if(c&&c.onError)c.onError(a)}})},onError:function(a){if(c&&c.onError)c.onError(a)},parent:this};a.Datastore.getInstance().shouldSendOffline("DELETE")?a.Datastore.getInstance().sendOffline("DELETE",b,null,null,e):a.Datastore.getInstance().deleteOnServer(b,e)};a.Pegawai.prototype.getIdtaksi=function(){return this.data.idtaksi};a.Pegawai.prototype.setIdtaksi=function(a){this.data.idtaksi=a};a.Pegawai.prototype.getNama=function(){return this.data.nama};
a.Pegawai.prototype.setNama=function(a){this.data.nama=a};a.Pegawai.prototype.getNip=function(){return this.data.nip};a.Pegawai.prototype.setNip=function(a){this.data.nip=a};a.Pegawai.prototype.getNoplat=function(){return this.data.noplat};a.Pegawai.prototype.setNoplat=function(a){this.data.noplat=a};a.Pegawai.prototype.getPerusahaan=function(){return this.data.perusahaan};a.Pegawai.prototype.setPerusahaan=function(a){this.data.perusahaan=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.User={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.User=function(c,b){this.init();"undefined"!==typeof c&&this.setUserName(c);"undefined"!==typeof b&&this.setPassword(b);this.initDatastoreIfNeeded=function(b){if(!1===a.Datastore.isInstantiated())if("undefined"!==typeof this.getUserName()&&"undefined"!==typeof this.getPassword())a.Datastore.configureWithCredentials(this);else if("getSessionToken"in this&&"undefined"!==typeof this.getSessionToken()&&this.getSessionToken())a.Datastore.configureWithUserSessionToken(this);else if("undefined"!==
typeof b&&b)a.Datastore.configurePlain(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS);else throw Error("The Datastore needs to be configured with user credentials or a session token for this method to work.");};this.save=function(b,c){this.initDatastoreIfNeeded(!1);a.AbstractClientDataModel.prototype.save.apply(this,[b,c])};this.requestNewPassword=function(){a.Datastore.getInstance().postOnServer(this,{onOk:function(a){},onError:function(a){}},"models/requestResetPassword/")};this.resetPassword=
function(b,c){var f={onOk:function(){this.parent.setOffline(this.wasLocalSave||!1);a.Datastore.configure(this.parent);if(c&&c.onOk)c.onOk()},onError:function(a){if(c&&c.onError)c.onError(a)},parent:this};this.setPassword(b);a.Datastore.getInstance().shouldSendOffline("PUT")?(f.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("PUT",this.getHref(),this,void 0,f)):a.Datastore.getInstance().updateOnServer(this,f)};this.requestSessionToken=function(a,b){this.requestSessionTokenWithRefreshToken(void 0,
a,b)};this.requestSessionTokenWithRefreshToken=function(b,c,f){b=b||void 0;this.initDatastoreIfNeeded("undefined"===b?!1:!0);var g=f;"undefined"!==typeof c&&c&&(g={onOk:function(b){var c=b.sessionToken||"";if(""===c){if("undefined"!==typeof f&&f.onError)f.onError(new a.ApiomatRequestError(a.Status.NO_TOKEN_RECEIVED,200))}else if(this.parent.setSessionToken(c),a.Datastore.configureWithUserSessionToken(this.parent),"undefined"!==typeof f&&f.onOk)f.onOk(b)},onError:function(a){if("undefined"!==typeof f&&
f.onError)f.onError(a)},parent:this});"undefined"===typeof b?a.Datastore.getInstance().requestSessionToken(g):a.Datastore.getInstance().requestSessionTokenWithRefreshToken(b,g)}};a.User.AOMBASEURL="https://apiomat.org/yambas/rest/apps/Taksi";a.User.AOMAPIKEY="7623755089510222796";a.User.AOMSYS="LIVE";a.User.AOMSDKVERSION="1.15.11-2477";a.User.getUsers=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.User,c,b,!1)};a.User.getUsersAndRefHref=function(c,b,e){a.Datastore.getInstance().loadListFromServerWithClass(a.User,
c,b,e)};a.User.getUsersCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.User,void 0,c,b)};a.User.prototype=new a.AbstractClientDataModel;a.User.prototype.constructor=a.User;a.User.prototype.loadMe=function(c){this.initDatastoreIfNeeded(!1);a.Datastore.getInstance().loadFromServer("models/me",c,this,!1)};a.User.prototype.init=function(){this.data={};this.data.dynamicAttributes={}};a.User.prototype.getSimpleName=function(){return"User"};a.User.prototype.getModuleName=function(){return"Basics"};
a.User.prototype.getDateOfBirth=function(){var a=this.data.dateOfBirth;return"undefined"!=typeof a?new Date(a):void 0};a.User.prototype.setDateOfBirth=function(a){this.data.dateOfBirth=a.getTime()};a.User.prototype.getFirstName=function(){return this.data.firstName};a.User.prototype.setFirstName=function(a){this.data.firstName=a};a.User.prototype.getLastName=function(){return this.data.lastName};a.User.prototype.setLastName=function(a){this.data.lastName=a};a.User.prototype.getLocLatitude=function(){var a=
this.data.loc;if(a)return a[0]};a.User.prototype.getLocLongitude=function(){var a=this.data.loc;if(a)return a[1]};a.User.prototype.setLocLatitude=function(a){var b=this.data.loc;b?b[0]=a:b=[a,void 0];this.data.loc=b};a.User.prototype.setLocLongitude=function(a){var b=this.data.loc;b?b[1]=a:b=[0,a];this.data.loc=b};a.User.prototype.getPassword=function(){return this.data.password};a.User.prototype.setPassword=function(a){this.data.password=a};a.User.prototype.getRefreshToken=function(){return this.data.refreshToken};
a.User.prototype.getSessionToken=function(){return this.data.sessionToken};a.User.prototype.setSessionToken=function(a){this.data.sessionToken=a};a.User.prototype.getSessionTokenExpirationDate=function(){var a=this.data.sessionTokenExpirationDate;return"undefined"!=typeof a?new Date(a):void 0};a.User.prototype.getUserName=function(){return this.data.userName};a.User.prototype.setUserName=function(a){this.data.userName=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Role={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Role=function(){this.init()};a.Role.getRoles=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Role,c,b,!1)};a.Role.getRolesAndRefHref=function(c,b,e){a.Datastore.getInstance().loadListFromServerWithClass(a.Role,c,b,e)};a.Role.getRolesCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Role,void 0,c,b)};a.Role.prototype=new a.AbstractClientDataModel;a.Role.prototype.constructor=a.Role;a.Role.prototype.init=function(){this.data={}};a.Role.prototype.getSimpleName=
function(){return"Role"};a.Role.prototype.getModuleName=function(){return"Basics"};a.Role.prototype.getMembers=function(){return this.data.members};a.Role.prototype.setMembers=function(a){this.data.members=a};a.Role.prototype.getName=function(){return this.data.name};a.Role.prototype.setName=function(a){this.data.name=a}})("undefined"===typeof exports?Apiomat:exports);